import { consumerFinanceImportExampleV1 } from "@telegram-system/shared";
import type { FinanceLocale } from "./i18n/core";

export const financeImportTemplate = JSON.stringify(
  consumerFinanceImportExampleV1,
  null,
  2,
);

const details: Record<FinanceLocale, string> = {
  en: `

GENERAL RULES
• File: one UTF-8 JSON document, up to 10 MB and 5,000 rows total including transaction items; one transaction may contain up to 100 items.
• A file downloaded with “Export data” already uses this format and can be uploaded directly.
• format and version must exactly match the template. mode is "ADD" (keep current records) or "REPLACE" (atomically delete the current ledger/planning data and load only this file). The switch in the import window overrides the file mode. Profile identity, access and paid plan are never replaced.
• Every object needs a unique ref within its section. A ref is your local identifier (for example "cash-uah"), not a database ID.
• Relations use ...Ref fields and must point to ref values included in this same file. Import referenced accounts/categories/goals/investments before using their refs conceptually; physical JSON order does not matter.
• Amounts are strings with a decimal point: "1250.50". Do not add spaces, commas or currency symbols. Opening balance may be negative; other amounts must be positive, while a valuation may be zero.
• Currency is a three-letter uppercase code such as UAH, USD, EUR or PLN.
• Date/time values are ISO-8601, preferably UTC: "2026-09-08T09:30:00.000Z". Timezones use IANA names such as "Europe/Kyiv".
• Empty sections may be [] or omitted. Field names are case-sensitive. Unknown fields and invalid enum values are rejected.
• The server validates the entire file first, automatically aligns each investment's startedAt/closedAt with its earliest/latest imported cash flow or valuation, downloads any missing official historical currency rates, and writes everything in one database transaction. For weekends and holidays it uses the latest published rate on or before the operation date. Do not replace historical rates with today's rate. One invalid row rolls back the whole import.
• In ADD mode, uploading the exact same JSON document again is detected and does not create duplicates. REPLACE always makes the current data match the uploaded file.
• During upload the window shows streamed validation, rate preparation and per-section write progress. You may cancel while the request is active.
• Analytics and balances are recalculated from imported records. Billing plan, bot or AI credentials and Telegram identity are intentionally not portable.

MIGRATION STRATEGY — DO NOT COPY LEGACY CATEGORIES BLINDLY
1. Inventory the source first: accounts and their currencies/balances, transactions, transfers between own accounts, recurring commitments, debts, savings, investments and budgets. Choose one cutoff date and preserve original timestamps.
2. Create accounts for real places where spendable money is held. openingBalance is the balance immediately before the first imported operation, not today's balance. After conversion, replay the file and verify each final account balance against the source.
3. Convert movements between the user's own accounts to transfers, never to income plus expense. Currency exchange between own accounts is also one transfer with fromAmount and toAmount.
4. A positive cash movement is not automatically income. Refunds and money returned to you use INCOME + REIMBURSEMENT; money received to pay on somebody else's behalf uses INCOME + PASS_THROUGH; paying back money you owe uses EXPENSE + DEBT_REPAYMENT. PASS_THROUGH is never valid for an EXPENSE. An outgoing payment made entirely on somebody else's behalf uses EXPENSE + ORDINARY with economicAmount "0"; if only part was theirs, economicAmount is only the user's share. Non-economic movements have economicAmount "0". Ordinary salary/sales use INCOME + ORDINARY and economicAmount equal to the user's real income.
5. For a shared purchase, transaction amount is the full card/cash charge, purpose is ORDINARY, economicAmount is only the user's share, and every unpaid participant is an OWED_TO_ME debt. When someone pays back later, import that income transaction as REIMBURSEMENT with economicAmount "0" and use it as settlementTransactionRef for the settled debt.
6. Do not leave subscriptions or repeating bills only in a “Subscriptions” category. Keep historical charges as transactions and create regularPayments for the future schedule. Set necessity once on an EXPENSE category to make it the default for its ordinary transactions and regularPayments; an explicit necessity on a transaction or regularPayment overrides that default. Use REQUIRED, DISCRETIONARY or UNSPECIFIED so analytics can separate essential and optional spending.
7. Convert money owed by/to the user to debts. A settled debt needs its real settlement transaction; that transaction changes the account balance but must not inflate income or expense.
8. Convert investment positions to investments, deposits/withdrawals to investmentCashFlows, and known market/business values to investmentValuations. Never import an investment contribution as ordinary expense or its return as ordinary income.
9. Convert savings envelopes/goals to savingsGoals and allocation history to savingsMovements. These movements reserve existing money and do not create income or expense.
10. Convert category budgets to limits. Use reminders only for notifications that are not repeating payments. Build a useful parent/child category tree instead of preserving accidental source-app folders.
11. Avoid double counting: one real event must have one cash movement. Do not also create ordinary income/expense for a transfer, investment cash flow, savings allocation or zero-economic settlement.
12. Before upload validate: refs resolve, account currencies match operation currencies, amounts use decimal strings, timestamps/timezones are explicit, final balances reconcile, and income/expense totals include only the user's economic share.

PROMPT FOR CONVERTING ANY SOURCE WITH AI
“Convert the attached finance export into format telegram-system.consumer-finance version 1, using the complete schema and example below. Inspect the entire source before converting it. Populate every applicable section: accounts, categories, transactions with items, transfers, limits, reminders, debts, regularPayments, savingsGoals, savingsMovements, investments, investmentCashFlows and investmentValuations. Do not emit an empty placeholder for a section when the source contains matching data; omit only sections that are genuinely absent. Do not merely rename old categories. Preserve full cash movement in amount and only my economic share in economicAmount. Enforce these exact purpose/type pairs: REIMBURSEMENT and PASS_THROUGH require type INCOME; DEBT_REPAYMENT requires type EXPENSE; never emit EXPENSE + PASS_THROUGH. For an outgoing payment made on somebody else's behalf, use EXPENSE + ORDINARY and set economicAmount to my share ("0" when none of it is mine). Never count transfers, reimbursements, debt settlements, savings allocations or investment movements as ordinary income/expense. Generate unique stable ref values and make every ...Ref resolve inside the same file. Ask focused questions before producing the final file instead of guessing ownership, opening balances, debt status, recurrence, necessity, savings allocation or investment value. Reconcile every final account balance. After all questions are resolved, return exactly one valid JSON object with no Markdown fence, comments, explanation or text before/after it.”

SECTIONS AND FIELDS
settings — optional profile settings: defaultCurrency, timezone, locale (uk | ru | en), displayName (up to 120 characters).
accounts — accounts. Required: ref, name, type (CASH | CARD | SAVINGS | OTHER), currency. Optional: emoji (Unicode/custom emoji or an existing immutable image source), openingBalance, archivedAt.
categories — category tree. Required: ref, name, type (INCOME | EXPENSE). Optional: parentRef, emoji (Unicode/custom emoji or an existing immutable image source), necessity (UNSPECIFIED | REQUIRED | DISCRETIONARY for an EXPENSE-category default), key, archivedAt. The category default is applied to ordinary EXPENSE transactions and regularPayments that reference it when they omit their own necessity; an explicit row necessity wins. Parent and child must have the same type.
transactions — income/expenses. Required: ref, accountRef, type, amount, occurredAt. Optional: categoryRef, recurringPaymentRef (a historical-payment link to a regularPayments ref), economicAmount, purpose (ORDINARY | REIMBURSEMENT | PASS_THROUGH | DEBT_REPAYMENT), necessity (UNSPECIFIED | REQUIRED | DISCRETIONARY), description, merchantDisplay, items[]. A recurringPaymentRef row must be an ORDINARY EXPENSE on the same account as the subscription; it becomes a confirmed historical payment. REIMBURSEMENT and PASS_THROUGH require type INCOME; DEBT_REPAYMENT requires type EXPENSE. EXPENSE + PASS_THROUGH is invalid: an outgoing payment made on somebody else's behalf uses ORDINARY with economicAmount equal to the user's share, including "0" when fully paid for the other person. Non-ordinary purposes have zero economic impact and cannot use a category. Type must match the category. Each item requires displayName and totalAmount; quantity, unitPrice, categoryRef and free-form metadata are optional.
transfers — between two accounts. Required: ref, fromAccountRef, toAccountRef, fromAmount, toAmount, occurredAt. Accounts must differ. Optional: description.
limits — monthly budgets. Required: ref, categoryRef pointing to an EXPENSE category, amount, currency.
reminders — monthly notifications that do not create transactions. Required: ref, name, amount, currency, dayOfMonth (1–31), nextOccurrenceAt (the next notification occurrence after the import cutoff). Optional: reminderOffsetMinutes (how many minutes before that occurrence to notify; non-negative integer), enabled.
debts — amounts the user owes or expects back. Required: ref, accountRef, direction (I_OWE means the user owes; OWED_TO_ME means another person owes the user), name, amount, dueAt, scheduleTimezone (IANA timezone giving the due date its calendar meaning). Optional: status (OPEN | SETTLED), note. SETTLED also requires settledAt and settlementTransactionRef to one matching imported transaction on the same account, with EXPENSE for I_OWE or INCOME for OWED_TO_ME and the same amount.
regularPayments — recurring payment schedules, including subscriptions. Required: ref, accountRef, name, amount, recurrence (DAILY | WEEKLY | MONTHLY | YEARLY), nextOccurrenceAt (next due occurrence after the import cutoff), scheduleTimezone (IANA timezone used for calendar recurrence). Optional: intervalCount (integer 1–3650, default 1), categoryRef pointing to EXPENSE, status (ACTIVE | PAUSED | CANCELED), necessity (UNSPECIFIED unknown, REQUIRED essential, DISCRETIONARY optional), note. To import subscription history, create the past ordinary EXPENSE rows in transactions and put recurringPaymentRef equal to this payment ref on every matching row. The historical row must use the same account; its amount may differ from the current scheduled amount. This creates a confirmed payment occurrence, so it appears in the subscription history and as a recurring expense in analytics. Examples: every 90 days is recurrence DAILY with intervalCount 90; every two weeks is WEEKLY with intervalCount 2. Import does not create a transaction automatically for nextOccurrenceAt.
savingsGoals — goals. Required: ref, name, targetAmount, currency. Optional: initialAmount for money saved before the imported movement history, targetDate, note, status (ACTIVE | COMPLETED | ARCHIVED).
savingsMovements — allocations. Required: ref, accountRef, kind, amount, occurredAt. ALLOCATE needs toGoalRef; RELEASE needs fromGoalRef; REALLOCATE needs two different goal refs. Goal/account currencies must match; at every point in chronological order, the linked movement balance must stay non-negative. initialAmount is preserved separately and cannot fund a RELEASE row. Optional: linkedTransferRef, note.
investments — investments. Required: ref, name, type, currency, startedAt. type: BUSINESS | REAL_ESTATE | SECURITIES | CRYPTO | DIGITAL_ASSET | PHYSICAL_ASSET | OTHER. Optional: description, status (ACTIVE | CLOSED | ARCHIVED), closedAt. A CLOSED investment's closedAt must be at or after every related cash-flow occurredAt and valuation valuedAt; use the real final event time, not the start of that calendar day.
investmentCashFlows — real account movements, separate from ordinary expense/income. Required: ref, investmentRef, accountRef, kind (CONTRIBUTION means money invested; RETURN means any money received back), amount, occurredAt. Optional: note.
investmentValuations — estimated asset value history; the latest non-corrected value is current value. Required: ref, investmentRef, value, valuedAt. Optional: correctsRef pointing to an earlier mistaken valuation of the same investment, createdAt (ISO-8601 tie-break timestamp), note. One valuation can only be corrected once. Result is current value + all RETURN flows − all CONTRIBUTION flows; return percentage divides that result by total contributions when they are non-zero.

EXAMPLE
`,
  uk: `

ЗАГАЛЬНІ ПРАВИЛА
• Файл: один JSON-документ у UTF-8, до 10 МБ і 5 000 записів загалом разом із позиціями транзакцій; в одній транзакції може бути до 100 позицій.
• Файл, завантажений кнопкою «Експортувати дані», уже має цей формат і готовий до імпорту.
• format і version мають збігатися із шаблоном. mode: "ADD" зберігає поточні записи, "REPLACE" атомарно видаляє поточні фінансові/планові дані й завантажує лише файл. Перемикач у вікні імпорту має пріоритет над mode у файлі. Ідентичність, доступ і платний тариф не замінюються.
• Кожен об’єкт має унікальний ref у межах свого розділу. Це ваш локальний ідентифікатор (наприклад "cash-uah"), а не ID з бази даних.
• Зв’язки задаються полями ...Ref і посилаються на ref із цього самого файлу. Порядок об’єктів у JSON не має значення.
• Суми передавайте рядками з крапкою: "1250.50", без пробілів, ком і символів валют. openingBalance може бути від’ємним; інші суми мають бути додатними, а оцінка інвестиції може дорівнювати нулю.
• Валюта — три великі літери: UAH, USD, EUR, PLN тощо.
• Дата й час — ISO-8601, бажано UTC: "2026-09-08T09:30:00.000Z". Часовий пояс — IANA, наприклад "Europe/Kyiv".
• Порожні розділи можна передати як [] або пропустити. Регістр назв полів важливий. Невідомі поля та некоректні enum-значення відхиляються.
• Сервер спочатку перевіряє весь файл, автоматично узгоджує startedAt/closedAt кожної інвестиції з найранішою/найпізнішою датою її імпортованих грошових потоків та оцінок, завантажує відсутні офіційні історичні курси валют і лише потім записує все однією транзакцією. Для вихідних і свят використовується останній опублікований курс на дату операції або раніше. Не замінюйте історичний курс сьогоднішнім. Помилка в одному рядку скасовує весь імпорт.
• У режимі ADD повторне завантаження точно такого самого JSON не дублює дані. REPLACE завжди приводить поточні дані у відповідність до файлу.
• У вікні в реальному часі показуються етапи перевірки, підготовки курсів і запису кожного розділу. Активний імпорт можна скасувати.
• Аналітика й баланси перераховуються. Тариф, облікові дані бота/AI та Telegram-ідентичність не переносяться.

СТРАТЕГІЯ МІГРАЦІЇ — НЕ КОПІЮЙТЕ СТАРІ КАТЕГОРІЇ МЕХАНІЧНО
1. Спочатку перелічіть рахунки, операції, перекази між власними рахунками, регулярні зобов’язання, борги, накопичення, інвестиції та бюджети. Оберіть дату початку й збережіть реальні дати.
2. Рахунки — це реальні місця з доступними коштами. openingBalance дорівнює балансу безпосередньо перед першою імпортованою операцією. Після перетворення звірте кінцевий баланс кожного рахунку з джерелом.
3. Рух між власними рахунками, включно з обміном валют, перетворюйте на один transfer, а не на дохід і витрату.
4. Плюс на рахунку не завжди є доходом. Повернення й компенсації мають INCOME + REIMBURSEMENT; гроші, отримані для оплати за іншу людину, — INCOME + PASS_THROUGH; повернення вашого боргу — EXPENSE + DEBT_REPAYMENT. PASS_THROUGH ніколи не можна використовувати з EXPENSE. Вихідний платіж повністю за іншу людину має EXPENSE + ORDINARY та economicAmount "0"; якщо частина витрати ваша, economicAmount дорівнює лише вашій частці. Неекономічні рухи мають economicAmount "0". Зарплата/продаж — INCOME + ORDINARY з реальною економічною сумою.
5. У спільній покупці amount — повне списання, purpose — ORDINARY, economicAmount — лише ваша частка, а несплачені частки інших людей — борги OWED_TO_ME. Пізніше повернення грошей — INCOME з REIMBURSEMENT та economicAmount "0"; цю транзакцію вкажіть як settlementTransactionRef погашеного боргу.
6. Підписки не повинні залишатися лише категорією. Історичні списання збережіть як transactions, майбутній розклад — regularPayments. Укажіть necessity один раз в EXPENSE-категорії, щоб він став типовим для її звичайних transactions і regularPayments; явне necessity у transaction або regularPayment має пріоритет. Використовуйте REQUIRED, DISCRETIONARY або UNSPECIFIED.
7. Суми, які ви винні або мають повернути вам, перетворіть на debts. Погашення змінює баланс рахунку, але не збільшує дохід/витрату.
8. Позиції перенесіть у investments, внесення/повернення — investmentCashFlows, відомі вартості — investmentValuations. Внесок не є звичайною витратою, повернення — звичайним доходом.
9. Конверти й цілі — savingsGoals, розподіли коштів — savingsMovements. Вони резервують наявні гроші, але не створюють доходу чи витрати.
10. Бюджети категорій перенесіть у limits, а reminders використовуйте лише для нагадувань, які не є регулярними платежами. Побудуйте корисне дерево категорій замість випадкових папок старої системи.
11. Не дублюйте одну подію: transfer, інвестиційний рух, розподіл накопичень або погашення з нульовим економічним впливом не повинні мати другу звичайну транзакцію.
12. Перед імпортом перевірте refs, валюти, десяткові рядки сум, дати/часові пояси, кінцеві баланси й те, що аналітика містить тільки вашу економічну частку.

ПРОМПТ ДЛЯ ПЕРЕТВОРЕННЯ БУДЬ-ЯКОГО ДЖЕРЕЛА ШІ
«Перетвори прикріплений фінансовий експорт у формат telegram-system.consumer-finance версії 1 за повною схемою та прикладом нижче. Спочатку проаналізуй усе джерело. Заповни кожний застосовний розділ: accounts, categories, transactions з items, transfers, limits, reminders, debts, regularPayments, savingsGoals, savingsMovements, investments, investmentCashFlows та investmentValuations. Не залишай порожній масив, якщо у джерелі є відповідні дані; пропускай лише справді відсутні розділи. Не перейменовуй старі категорії механічно. У amount збережи повний рух коштів, в economicAmount — лише мою економічну частку. Дотримуйся точних пар purpose/type: REIMBURSEMENT і PASS_THROUGH потребують type INCOME; DEBT_REPAYMENT потребує type EXPENSE; ніколи не створюй EXPENSE + PASS_THROUGH. Для вихідного платежу за іншу людину використовуй EXPENSE + ORDINARY та вкажи в economicAmount мою частку ("0", якщо моєї частки немає). Не рахуй перекази, компенсації, погашення боргів, розподіли накопичень або інвестиційні рухи звичайним доходом/витратою. Створи унікальні стабільні ref і перевір, що кожне ...Ref посилається на об’єкт у цьому самому файлі. До фінальної відповіді постав конкретні запитання замість припущень про власника коштів, openingBalance, статус боргу, періодичність, necessity, розподіл накопичень або вартість інвестиції. Звір кінцевий баланс кожного рахунку. Після уточнень поверни рівно один валідний JSON-об’єкт без Markdown, коментарів, пояснень і тексту до чи після нього».

РОЗДІЛИ ТА ПОЛЯ
settings — необов’язкові налаштування профілю: defaultCurrency, timezone, locale (uk | ru | en), displayName (до 120 символів).
accounts — рахунки. Обов’язкові: ref, name, type (CASH | CARD | SAVINGS | OTHER), currency. Необов’язкові: emoji (Unicode/custom emoji або наявне незмінне джерело зображення), openingBalance, archivedAt.
categories — дерево категорій. Обов’язкові: ref, name, type (INCOME | EXPENSE). Необов’язкові: parentRef, emoji (Unicode/custom emoji або наявне незмінне джерело зображення), necessity (UNSPECIFIED | REQUIRED | DISCRETIONARY як типове значення для EXPENSE-категорії), key, archivedAt. Типове значення категорії застосовується до звичайних EXPENSE-transactions і regularPayments з цією категорією, якщо вони не мають власного necessity; явне значення рядка має пріоритет. Тип батьківської та дочірньої категорії має збігатися.
transactions — доходи й витрати. Обов’язкові: ref, accountRef, type, amount, occurredAt. amount — повний рух на рахунку, economicAmount — лише частина, що входить в аналітику доходів/витрат. Необов’язкові: categoryRef, recurringPaymentRef (посилання історичної оплати на ref з regularPayments), economicAmount, purpose (ORDINARY | REIMBURSEMENT | PASS_THROUGH | DEBT_REPAYMENT), necessity (UNSPECIFIED | REQUIRED | DISCRETIONARY), description, merchantDisplay, items[]. Рядок з recurringPaymentRef має бути ORDINARY EXPENSE на тому самому рахунку, що й підписка; він стане підтвердженою історичною оплатою. REIMBURSEMENT і PASS_THROUGH потребують type INCOME; DEBT_REPAYMENT потребує type EXPENSE. EXPENSE + PASS_THROUGH є помилкою: вихідний платіж за іншу людину має ORDINARY з economicAmount, що дорівнює частці користувача, включно з "0", якщо платіж повністю за іншу людину. Не-ORDINARY операції мають economicAmount "0" і не можуть мати категорію. Для кожного items[] обов’язкові displayName і totalAmount; quantity, unitPrice, categoryRef та довільний об’єкт metadata необов’язкові.
transfers — перекази між рахунками. Обов’язкові: ref, fromAccountRef, toAccountRef, fromAmount, toAmount, occurredAt. Рахунки мають відрізнятися. Необов’язкове: description.
limits — місячні бюджети. Обов’язкові: ref, categoryRef на EXPENSE-категорію, amount, currency.
reminders — щомісячні повідомлення, які не створюють транзакцію. Обов’язкові: ref, name, amount, currency, dayOfMonth (1–31), nextOccurrenceAt — найближче майбутнє спрацювання після дати імпорту. Необов’язкові: reminderOffsetMinutes — за скільки хвилин до події повідомити, enabled.
debts — суми, які винен користувач або мають повернути йому. Обов’язкові: ref, accountRef, direction (I_OWE — винен користувач; OWED_TO_ME — винні користувачу), name, amount, dueAt, scheduleTimezone — IANA-зона календарної дати боргу. Необов’язкові: status (OPEN | SETTLED), note. Для SETTLED також потрібні settledAt і settlementTransactionRef на транзакцію того самого рахунку й суми: EXPENSE для I_OWE або INCOME для OWED_TO_ME.
regularPayments — розклади регулярних оплат, зокрема підписок. Обов’язкові: ref, accountRef, name, amount, recurrence (DAILY | WEEKLY | MONTHLY | YEARLY), nextOccurrenceAt — найближча майбутня дата оплати, scheduleTimezone — IANA-зона календарного повторення. Необов’язкові: intervalCount (ціле число 1–3650, типово 1), categoryRef на EXPENSE-категорію, status (ACTIVE | PAUSED | CANCELED), necessity (UNSPECIFIED — невідомо, REQUIRED — обов’язково, DISCRETIONARY — за бажанням), note. Щоб імпортувати історію підписки, створіть минулі звичайні EXPENSE-рядки в transactions і в кожному вкажіть recurringPaymentRef, рівний ref цієї оплати. Історичний рядок має використовувати той самий рахунок; його сума може відрізнятися від поточної суми за розкладом. Це створює підтверджену оплату, тому вона буде в історії підписки та в аналітиці регулярних витрат. Приклади: кожні 90 днів — recurrence DAILY та intervalCount 90; кожні два тижні — WEEKLY та intervalCount 2. Імпорт не створює транзакцію автоматично.
savingsGoals — цілі заощаджень. Обов’язкові: ref, name, targetAmount, currency. Необов’язкові: initialAmount для суми, накопиченої до імпортованої історії рухів, targetDate, note, status (ACTIVE | COMPLETED | ARCHIVED).
savingsMovements — розподіл заощаджень. Обов’язкові: ref, accountRef, kind, amount, occurredAt. ALLOCATE потребує toGoalRef; RELEASE — fromGoalRef; REALLOCATE — дві різні цілі. Валюти цілі й рахунку мають збігатися; у кожний момент за хронологією баланс пов’язаних рухів не може бути від’ємним. initialAmount зберігається окремо й не може фінансувати рядок RELEASE. Необов’язкові: linkedTransferRef, note.
investments — інвестиції. Обов’язкові: ref, name, type, currency, startedAt. type: BUSINESS | REAL_ESTATE | SECURITIES | CRYPTO | DIGITAL_ASSET | PHYSICAL_ASSET | OTHER. Необов’язкові: description, status (ACTIVE | CLOSED | ARCHIVED), closedAt. Для CLOSED значення closedAt має бути не раніше за occurredAt усіх пов’язаних грошових потоків і valuedAt усіх оцінок; використовуйте реальний час останньої події, а не початок цього календарного дня.
investmentCashFlows — реальні рухи на рахунку окремо від звичайного доходу/витрати. Обов’язкові: ref, investmentRef, accountRef, kind (CONTRIBUTION — вкладено; RETURN — будь-які кошти отримано назад), amount, occurredAt. Необов’язкове: note.
investmentValuations — історія оцінки активу; остання невиправлена оцінка є поточною вартістю. Обов’язкові: ref, investmentRef, value, valuedAt. Необов’язкові: correctsRef на помилкову попередню оцінку тієї самої інвестиції, createdAt (ISO-8601 для порядку за однакової дати), note. Результат = поточна вартість + усі RETURN − усі CONTRIBUTION; відсоток ділиться на суму внесків, якщо вона не нульова.

ПРИКЛАД
`,
  ru: `

ОБЩИЕ ПРАВИЛА
• Файл: один JSON-документ в UTF-8, до 10 МБ и 5 000 записей всего вместе с позициями транзакций; в одной транзакции может быть до 100 позиций.
• Файл, скачанный кнопкой «Экспортировать данные», уже имеет этот формат и готов к импорту.
• format и version должны совпадать с шаблоном. mode: "ADD" сохраняет текущие записи, "REPLACE" атомарно удаляет текущие финансовые/плановые данные и загружает только файл. Переключатель в окне импорта имеет приоритет над mode файла. Личность, доступ и платный тариф не заменяются.
• У каждого объекта должен быть уникальный ref внутри его раздела. Это ваш локальный идентификатор (например "cash-uah"), а не ID из базы данных.
• Связи задаются полями ...Ref и указывают на ref из этого же файла. Фактический порядок объектов в JSON значения не имеет.
• Суммы передаются строками с точкой: "1250.50", без пробелов, запятых и символов валют. openingBalance может быть отрицательным; остальные суммы должны быть положительными, а оценка инвестиции может быть нулевой.
• Валюта — три заглавные буквы: UAH, USD, EUR, PLN и т. д.
• Дата и время — ISO-8601, желательно UTC: "2026-09-08T09:30:00.000Z". Часовой пояс — IANA, например "Europe/Kyiv".
• Пустой раздел можно передать как [] или не передавать. Регистр в названиях полей важен. Неизвестные поля и неверные enum-значения отклоняются.
• Сервер сначала проверяет весь файл, автоматически согласует startedAt/closedAt каждой инвестиции с самой ранней/поздней датой её импортируемых денежных потоков и оценок, загружает недостающие официальные исторические курсы валют и только затем записывает всё одной транзакцией. Для выходных и праздников используется последний опубликованный курс на дату операции или раньше. Не заменяйте исторический курс сегодняшним. Ошибка в одной строке отменяет весь импорт.
• В режиме ADD повторная загрузка того же JSON не создаёт дубликаты. REPLACE всегда приводит текущие данные в соответствие файлу.
• В окне в реальном времени показываются проверка, подготовка курсов и запись каждого раздела. Активный импорт можно отменить.
• Аналитика и балансы пересчитываются. Тариф, учётные данные бота/AI и Telegram-идентичность не переносятся.

СТРАТЕГИЯ МИГРАЦИИ — НЕ КОПИРУЙТЕ СТАРЫЕ КАТЕГОРИИ МЕХАНИЧЕСКИ
1. Сначала перечислите счета, операции, переводы между своими счетами, регулярные обязательства, долги, накопления, инвестиции и бюджеты. Выберите дату начала и сохраните реальные даты.
2. Счета — реальные места хранения доступных денег. openingBalance — баланс непосредственно перед первой импортируемой операцией. После преобразования сверьте конечный баланс каждого счёта с источником.
3. Движение между своими счетами, включая обмен валют, переносите как один transfer, а не доход плюс расход.
4. Плюс на счёте не всегда является доходом. Возвраты и компенсации получают INCOME + REIMBURSEMENT; деньги, полученные для оплаты за другого человека, — INCOME + PASS_THROUGH; возврат вашего долга — EXPENSE + DEBT_REPAYMENT. PASS_THROUGH никогда нельзя использовать с EXPENSE. Исходящий платёж полностью за другого человека получает EXPENSE + ORDINARY и economicAmount "0"; если часть расхода ваша, economicAmount равен только вашей доле. Неэкономические движения имеют economicAmount "0". Зарплата/продажа — INCOME + ORDINARY с реальной экономической суммой.
5. В общей покупке amount — полное списание, purpose — ORDINARY, economicAmount — только ваша доля, а неоплаченные доли других людей — долги OWED_TO_ME. Поздний возврат денег — INCOME с REIMBURSEMENT и economicAmount "0"; эту транзакцию укажите как settlementTransactionRef погашенного долга.
6. Подписки не должны оставаться только категорией. Исторические списания сохраните как transactions, будущий график — regularPayments. Укажите necessity один раз в EXPENSE-категории, чтобы оно стало значением по умолчанию для её обычных transactions и regularPayments; явное necessity в transaction или regularPayment имеет приоритет. Используйте REQUIRED, DISCRETIONARY или UNSPECIFIED.
7. Суммы, которые должны вы или вам, перенесите в debts. Погашение меняет баланс счёта, но не увеличивает доход/расход.
8. Позиции перенесите в investments, взносы/возвраты — investmentCashFlows, известную стоимость — investmentValuations. Взнос не является обычным расходом, возврат — обычным доходом.
9. Конверты и цели — savingsGoals, распределения денег — savingsMovements. Они резервируют существующие деньги, но не создают доход или расход.
10. Бюджеты категорий перенесите в limits, reminders используйте только для напоминаний, которые не являются регулярными платежами. Постройте полезное дерево категорий вместо случайных папок старой системы.
11. Не дублируйте одно событие: transfer, инвестиционное движение, распределение накоплений или погашение с нулевым экономическим эффектом не должны иметь вторую обычную транзакцию.
12. До импорта проверьте refs, валюты, десятичные строки сумм, даты/часовые пояса, конечные балансы и то, что аналитика содержит только вашу экономическую долю.

ПРОМПТ ДЛЯ ПРЕОБРАЗОВАНИЯ ЛЮБОГО ИСТОЧНИКА ИИ
«Преобразуй прикреплённый финансовый экспорт в формат telegram-system.consumer-finance версии 1 по полной схеме и примеру ниже. Сначала проанализируй весь источник. Заполни каждый применимый раздел: accounts, categories, transactions с items, transfers, limits, reminders, debts, regularPayments, savingsGoals, savingsMovements, investments, investmentCashFlows и investmentValuations. Не оставляй пустой массив, если в источнике есть соответствующие данные; пропускай только действительно отсутствующие разделы. Не переименовывай старые категории механически. В amount сохрани полный денежный поток, в economicAmount — только мою экономическую долю. Соблюдай точные пары purpose/type: REIMBURSEMENT и PASS_THROUGH требуют type INCOME; DEBT_REPAYMENT требует type EXPENSE; никогда не создавай EXPENSE + PASS_THROUGH. Для исходящего платежа за другого человека используй EXPENSE + ORDINARY и укажи в economicAmount мою долю ("0", если моей доли нет). Не считай переводы, компенсации, погашения долгов, распределения накоплений или инвестиционные движения обычным доходом/расходом. Создай уникальные стабильные ref и проверь, что каждое ...Ref ссылается на объект в этом же файле. До финального ответа задай конкретные вопросы вместо догадок о владельце денег, openingBalance, статусе долга, периодичности, necessity, распределении накоплений или стоимости инвестиции. Сверь конечный баланс каждого счёта. После уточнений верни ровно один валидный JSON-объект без Markdown, комментариев, пояснений и текста до или после него».

РАЗДЕЛЫ И ПОЛЯ
settings — необязательные настройки профиля: defaultCurrency, timezone, locale (uk | ru | en), displayName (до 120 символов).
accounts — счета. Обязательные: ref, name, type (CASH | CARD | SAVINGS | OTHER), currency. Необязательные: emoji (Unicode/custom emoji или существующий неизменяемый источник изображения), openingBalance, archivedAt.
categories — дерево категорий. Обязательные: ref, name, type (INCOME | EXPENSE). Необязательные: parentRef, emoji (Unicode/custom emoji или существующий неизменяемый источник изображения), necessity (UNSPECIFIED | REQUIRED | DISCRETIONARY как значение по умолчанию для EXPENSE-категории), key, archivedAt. Значение категории применяется к обычным EXPENSE-transactions и regularPayments с этой категорией, если у них нет собственного necessity; явное значение строки имеет приоритет. Тип родительской и дочерней категории должен совпадать.
transactions — доходы и расходы. Обязательные: ref, accountRef, type, amount, occurredAt. amount — полный денежный поток по счёту, economicAmount — только часть, попадающая в аналитику доходов/расходов. Необязательные: categoryRef, recurringPaymentRef (ссылка исторической оплаты на ref из regularPayments), economicAmount, purpose (ORDINARY | REIMBURSEMENT | PASS_THROUGH | DEBT_REPAYMENT), necessity (UNSPECIFIED | REQUIRED | DISCRETIONARY), description, merchantDisplay, items[]. Строка с recurringPaymentRef должна быть ORDINARY EXPENSE на том же счёте, что и подписка; она станет подтверждённой исторической оплатой. REIMBURSEMENT и PASS_THROUGH требуют type INCOME; DEBT_REPAYMENT требует type EXPENSE. EXPENSE + PASS_THROUGH недопустим: исходящий платёж за другого человека получает ORDINARY с economicAmount, равным доле пользователя, включая "0", если платёж полностью сделан за другого. Не-ORDINARY операции имеют economicAmount "0" и не могут иметь категорию. Для каждого items[] обязательны displayName и totalAmount; quantity, unitPrice, categoryRef и произвольный объект metadata необязательны.
transfers — переводы между счетами. Обязательные: ref, fromAccountRef, toAccountRef, fromAmount, toAmount, occurredAt. Счета должны различаться. Необязательное: description.
limits — месячные бюджеты. Обязательные: ref, categoryRef на EXPENSE-категорию, amount, currency.
reminders — ежемесячные уведомления, которые не создают транзакцию. Обязательные: ref, name, amount, currency, dayOfMonth (1–31), nextOccurrenceAt — ближайшее будущее срабатывание после даты импорта. Необязательные: reminderOffsetMinutes — за сколько минут до события уведомить, enabled.
debts — суммы, которые должен пользователь или должны вернуть ему. Обязательные: ref, accountRef, direction (I_OWE — должен пользователь; OWED_TO_ME — должны пользователю), name, amount, dueAt, scheduleTimezone — IANA-зона календарной даты долга. Необязательные: status (OPEN | SETTLED), note. Для SETTLED также нужны settledAt и settlementTransactionRef на транзакцию того же счёта и суммы: EXPENSE для I_OWE или INCOME для OWED_TO_ME.
regularPayments — графики регулярных оплат, включая подписки. Обязательные: ref, accountRef, name, amount, recurrence (DAILY | WEEKLY | MONTHLY | YEARLY), nextOccurrenceAt — ближайшая будущая дата оплаты, scheduleTimezone — IANA-зона календарного повторения. Необязательные: intervalCount (целое число 1–3650, по умолчанию 1), categoryRef на EXPENSE-категорию, status (ACTIVE | PAUSED | CANCELED), necessity (UNSPECIFIED — неизвестно, REQUIRED — обязательно, DISCRETIONARY — по желанию), note. Чтобы импортировать историю подписки, создайте прошлые обычные EXPENSE-строки в transactions и в каждой укажите recurringPaymentRef, равный ref этой оплаты. Историческая строка должна использовать тот же счёт; её сумма может отличаться от текущей суммы по графику. Это создаёт подтверждённую оплату: она появится в истории подписки и в аналитике постоянных расходов. Примеры: каждые 90 дней — recurrence DAILY и intervalCount 90; каждые две недели — WEEKLY и intervalCount 2. Импорт не создаёт транзакцию автоматически.
savingsGoals — цели накоплений. Обязательные: ref, name, targetAmount, currency. Необязательные: initialAmount для суммы, накопленной до импортируемой истории движений, targetDate, note, status (ACTIVE | COMPLETED | ARCHIVED).
savingsMovements — распределение накоплений. Обязательные: ref, accountRef, kind, amount, occurredAt. ALLOCATE требует toGoalRef; RELEASE — fromGoalRef; REALLOCATE требует две разные цели. Валюты цели и счёта должны совпадать; в каждый момент по хронологии баланс связанных движений не может быть отрицательным. initialAmount сохраняется отдельно и не может финансировать строку RELEASE. Необязательные: linkedTransferRef, note.
investments — инвестиции. Обязательные: ref, name, type, currency, startedAt. type: BUSINESS | REAL_ESTATE | SECURITIES | CRYPTO | DIGITAL_ASSET | PHYSICAL_ASSET | OTHER. Необязательные: description, status (ACTIVE | CLOSED | ARCHIVED), closedAt. Для CLOSED значение closedAt должно быть не раньше occurredAt всех связанных денежных потоков и valuedAt всех оценок; используйте реальное время последнего события, а не начало этого календарного дня.
investmentCashFlows — реальные движения по счёту отдельно от обычного дохода/расхода. Обязательные: ref, investmentRef, accountRef, kind (CONTRIBUTION — вложено; RETURN — любые деньги получены обратно), amount, occurredAt. Необязательное: note.
investmentValuations — история оценки актива; последняя неисправленная оценка является текущей стоимостью. Обязательные: ref, investmentRef, value, valuedAt. Необязательные: correctsRef на ошибочную предыдущую оценку той же инвестиции, createdAt (ISO-8601 для порядка при одинаковой дате), note. Результат = текущая стоимость + все RETURN − все CONTRIBUTION; процент делится на сумму вкладов, если она не равна нулю.

ПРИМЕР
`,
};

const intro: Record<FinanceLocale, string> = {
  en: `FINANCE DATA IMPORT — FORMAT VERSION 1

Prepare one JSON file. You may include any combination of sections, but every referenced account/category/goal/investment must also be present in the same file.`,
  uk: `ІМПОРТ ДАНИХ FINANCE — ФОРМАТ ВЕРСІЇ 1

Підготуйте один JSON-файл. Можна передати будь-яке поєднання розділів, але кожен рахунок, категорія, ціль або інвестиція, на яку є посилання, також має бути в цьому файлі.`,
  ru: `ИМПОРТ ДАННЫХ FINANCE — ФОРМАТ ВЕРСИИ 1

Подготовьте один JSON-файл. Можно передать любое сочетание разделов, но каждый счёт, категория, цель или инвестиция, на которую есть ссылка, также должны присутствовать в этом файле.`,
};

export function financeImportInstructions(locale: FinanceLocale) {
  return `${intro[locale]}${details[locale]}${financeImportTemplate}`;
}
