import type { ReactNode } from "react";
import {
  ArrowLeftRight,
  BadgeDollarSign,
  Bot,
  CalendarClock,
  Download,
  Eye,
  FlaskConical,
  FolderPlus,
  History,
  Images,
  Link2,
  Megaphone,
  MessagesSquare,
  PanelTop,
  Pencil,
  Plus,
  RadioTower,
  ReceiptText,
  Settings2,
  ShieldCheck,
  Tags,
  Trash2,
  Upload,
  UserPlus,
  WalletCards,
  Workflow,
} from "lucide-react";

export type FeatureModalIconName =
  | "account"
  | "ad-sale"
  | "automation"
  | "bot"
  | "campaign"
  | "category"
  | "channel-settings"
  | "create"
  | "delete"
  | "edit"
  | "export"
  | "folder"
  | "generic"
  | "history"
  | "hypothesis"
  | "import"
  | "invite-link"
  | "member"
  | "message-template"
  | "network"
  | "preview"
  | "promo"
  | "role"
  | "schedule"
  | "transaction"
  | "transfer";

const iconProps = { size: 19, "aria-hidden": true } as const;

const featureModalIcons: Record<FeatureModalIconName, ReactNode> = {
  account: <WalletCards {...iconProps} />,
  "ad-sale": <BadgeDollarSign {...iconProps} />,
  automation: <Workflow {...iconProps} />,
  bot: <Bot {...iconProps} />,
  campaign: <Megaphone {...iconProps} />,
  category: <Tags {...iconProps} />,
  "channel-settings": <Settings2 {...iconProps} />,
  create: <Plus {...iconProps} />,
  delete: <Trash2 {...iconProps} />,
  edit: <Pencil {...iconProps} />,
  export: <Upload {...iconProps} />,
  folder: <FolderPlus {...iconProps} />,
  generic: <PanelTop {...iconProps} />,
  history: <History {...iconProps} />,
  hypothesis: <FlaskConical {...iconProps} />,
  import: <Download {...iconProps} />,
  "invite-link": <Link2 {...iconProps} />,
  member: <UserPlus {...iconProps} />,
  "message-template": <MessagesSquare {...iconProps} />,
  network: <RadioTower {...iconProps} />,
  preview: <Eye {...iconProps} />,
  promo: <Images {...iconProps} />,
  role: <ShieldCheck {...iconProps} />,
  schedule: <CalendarClock {...iconProps} />,
  transaction: <ReceiptText {...iconProps} />,
  transfer: <ArrowLeftRight {...iconProps} />,
};

export function featureModalIcon(name: FeatureModalIconName) {
  return featureModalIcons[name];
}

export function featureModalIconForTitle(title: ReactNode) {
  const value = typeof title === "string" ? title.trim().toLowerCase() : "";
  if (/\b(delete|remove|reset)\b|видал|удал/.test(value))
    return featureModalIcon("delete");
  if (/\bpromo\b/.test(value)) return featureModalIcon("promo");
  if (/\bcampaign\b/.test(value)) return featureModalIcon("campaign");
  if (/\bhypoth/.test(value)) return featureModalIcon("hypothesis");
  if (/\b(channel settings|channel appearance)\b/.test(value))
    return featureModalIcon("channel-settings");
  if (/\b(message template|autogenerated messages)\b/.test(value))
    return featureModalIcon("message-template");
  if (/\b(schedule|calendar|time posts?)\b|розклад|распис/.test(value))
    return featureModalIcon("schedule");
  if (/\b(ad sale|sale)\b/.test(value)) return featureModalIcon("ad-sale");
  if (/\bautomation\b/.test(value)) return featureModalIcon("automation");
  if (/\bfolder\b/.test(value)) return featureModalIcon("folder");
  if (/\bnetwork\b/.test(value)) return featureModalIcon("network");
  if (/\bmember\b/.test(value)) return featureModalIcon("member");
  if (/\brole\b/.test(value)) return featureModalIcon("role");
  if (/\baccount\b/.test(value)) return featureModalIcon("account");
  if (/\bcategory\b/.test(value)) return featureModalIcon("category");
  if (/\btransfer\b/.test(value)) return featureModalIcon("transfer");
  if (/\btransaction\b/.test(value)) return featureModalIcon("transaction");
  if (/\bbot\b/.test(value)) return featureModalIcon("bot");
  if (/\b(edit|update|change)\b|редаг|измен|редакт/.test(value))
    return featureModalIcon("edit");
  if (/\bhistory\b|істор|истор/.test(value)) return featureModalIcon("history");
  if (/\bimport\b|імпорт|импорт/.test(value)) return featureModalIcon("import");
  if (/\bexport\b|експорт|экспорт/.test(value))
    return featureModalIcon("export");
  if (/\bpreview\b|перегляд|просмотр/.test(value))
    return featureModalIcon("preview");
  if (/\b(connect|link|invite)\b|підключ|подключ|посилан|ссыл/.test(value))
    return featureModalIcon("invite-link");
  if (/\b(create|add|new)\b|створ|додат|нов|созд|добав/.test(value))
    return featureModalIcon("create");
  return featureModalIcon("generic");
}
