ALTER TYPE "FinanceTransactionPurpose" ADD VALUE IF NOT EXISTS 'REIMBURSEMENT';
ALTER TYPE "FinanceTransactionPurpose" ADD VALUE IF NOT EXISTS 'PASS_THROUGH';
ALTER TYPE "FinanceTransactionPurpose" ADD VALUE IF NOT EXISTS 'DEBT_REPAYMENT';
