"use client";

import { useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { FilePlus2, Pencil, Trash2 } from "lucide-react";
import type { TelegramChannelMessageTemplate } from "@telegram-system/shared";
import { IconAvatar } from "@/components/icons/icon-avatar";
import type { TelegramChannel, TelegramChannelNetwork } from "@/lib/api";
import {
  Button,
  Card,
  ErrorState,
  IconButton,
  LoadingState,
  Modal,
} from "@/components/ui/primitives";
import {
  telegramChannelMessageTemplatesApi,
  telegramMessageTemplateKeys,
} from "@/lib/features/telegram/telegram-channel-message-templates-api";
import {
  readTelegramChannelMessageTemplateDrafts,
  removeTelegramChannelMessageTemplateDraft,
  type TelegramChannelMessageTemplateDraft,
} from "./telegram-channel-message-template-draft";
import { TelegramChannelMessageTemplateEditor } from "./telegram-channel-message-template-editor";

type EditorState = {
  initial?:
    | TelegramChannelMessageTemplate
    | TelegramChannelMessageTemplateDraft;
  draftId: string;
};

const newDraftId = () => `template-${crypto.randomUUID()}`;

export function TelegramChannelMessageTemplatesModal({
  channels,
  networks,
  onClose,
}: {
  channels: TelegramChannel[];
  networks: TelegramChannelNetwork[];
  onClose: () => void;
}) {
  const queryClient = useQueryClient();
  const [editor, setEditor] = useState<EditorState | null>(null);
  const [draftRevision, setDraftRevision] = useState(0);
  const templates = useQuery({
    queryKey: telegramMessageTemplateKeys.list(),
    queryFn: telegramChannelMessageTemplatesApi.list,
  });
  const drafts = useMemo(
    () =>
      typeof window === "undefined"
        ? []
        : readTelegramChannelMessageTemplateDrafts(window.localStorage),
    // Re-read only when an editor returns or a draft is deleted.
    // eslint-disable-next-line react-hooks/exhaustive-deps
    [draftRevision, editor],
  );
  const removeSaved = useMutation({
    mutationFn: telegramChannelMessageTemplatesApi.remove,
    onSuccess: () =>
      queryClient.invalidateQueries({
        queryKey: telegramMessageTemplateKeys.all,
      }),
  });
  const deleteDraft = (id?: string) => {
    removeTelegramChannelMessageTemplateDraft(localStorage, id);
    setDraftRevision((value) => value + 1);
  };

  return (
    <Modal
      open
      onClose={onClose}
      title={editor ? "Edit message template" : "Autogenerated messages"}
      size="xl"
    >
      {editor ? (
        <TelegramChannelMessageTemplateEditor
          channels={channels}
          networks={networks}
          initial={editor.initial}
          draftId={editor.draftId}
          onBack={() => setEditor(null)}
          onSaved={() => {
            setEditor(null);
            setDraftRevision((value) => value + 1);
          }}
        />
      ) : (
        <div className="space-y-5">
          <div className="flex flex-wrap items-start justify-between gap-3">
            <p className="max-w-2xl text-sm leading-5 text-neutral-400">
              Create reusable Telegram channel lists from live links, TgStat
              settings and product prices. Saved templates are shared in this
              workspace; unfinished drafts stay on this device.
            </p>
            <Button
              type="button"
              onClick={() => setEditor({ draftId: newDraftId() })}
            >
              <FilePlus2 size={16} /> New template
            </Button>
          </div>
          {drafts.length ? (
            <section>
              <h3 className="mb-2 text-sm font-semibold text-neutral-200">
                Continue a draft
              </h3>
              <div className="grid gap-2 md:grid-cols-2">
                {drafts.map((draft) => (
                  <Card key={draft.id} className="flex items-center gap-3 p-3">
                    <button
                      type="button"
                      className="min-w-0 flex-1 text-left"
                      onClick={() =>
                        setEditor({ initial: draft, draftId: draft.id! })
                      }
                    >
                      <span className="flex items-center gap-2.5">
                        {draft.preview?.icon ? (
                          <IconAvatar
                            icon={draft.preview.icon}
                            label={draft.form.title || "Untitled template"}
                            size="sm"
                            decorative
                          />
                        ) : null}
                        <span className="min-w-0">
                          <span className="block truncate font-medium text-white">
                            {draft.form.title || "Untitled template"}
                          </span>
                          <span className="block text-xs text-neutral-500">
                            {draft.form.channelIds.length} channels · local
                            draft
                          </span>
                        </span>
                      </span>
                    </button>
                    <IconButton
                      type="button"
                      kind="delete"
                      aria-label="Delete draft"
                      title="Delete draft"
                      onClick={() => deleteDraft(draft.id)}
                    />
                  </Card>
                ))}
              </div>
            </section>
          ) : null}
          <section>
            <h3 className="mb-2 text-sm font-semibold text-neutral-200">
              Saved templates
            </h3>
            {templates.isLoading ? <LoadingState /> : null}
            {templates.isError ? (
              <ErrorState text="Could not load message templates." />
            ) : null}
            {!templates.isLoading && !templates.data?.length ? (
              <Card className="text-sm text-neutral-400">
                No saved templates yet. Create one or continue a local draft.
              </Card>
            ) : null}
            <div className="grid gap-2 md:grid-cols-2">
              {templates.data?.map((template) => (
                <Card key={template.id} className="flex items-center gap-3 p-3">
                  <button
                    type="button"
                    className="min-w-0 flex-1 text-left"
                    onClick={() =>
                      setEditor({
                        initial: template,
                        draftId: newDraftId(),
                      })
                    }
                  >
                    <p className="truncate font-medium text-white">
                      {template.title || "Untitled template"}
                    </p>
                    <p className="text-xs text-neutral-500">
                      {template.channelIds.length} channels · updated{" "}
                      {new Date(template.updatedAt).toLocaleDateString()}
                    </p>
                  </button>
                  <Button
                    type="button"
                    variant="secondary"
                    aria-label="Edit template"
                    onClick={() =>
                      setEditor({ initial: template, draftId: newDraftId() })
                    }
                  >
                    <Pencil size={16} />
                  </Button>
                  <Button
                    type="button"
                    variant="secondary"
                    aria-label="Delete template"
                    disabled={removeSaved.isPending}
                    onClick={() => removeSaved.mutate(template.id)}
                  >
                    <Trash2 size={16} />
                  </Button>
                </Card>
              ))}
            </div>
          </section>
        </div>
      )}
    </Modal>
  );
}
