"use client";
import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { AppShell } from "@/components/layout/app-shell";
import { Button, Card, FormField, Input, LoadingState, PageHeader } from "@/components/ui/primitives";
import { botBillingApi, financeAiConfigApi } from "@/lib/features/finance/bot-billing-api";
import { botBillingKeys } from "@/lib/query-keys";

export function GlobalBotConfigPage() { const providers = useQuery({ queryKey: botBillingKeys.workspaceProviders(), queryFn: botBillingApi.workspaceProviders }); const ai = useQuery({ queryKey: botBillingKeys.workspaceFinanceAi(), queryFn: financeAiConfigApi.workspace }); return <AppShell><PageHeader title="Global bot config" subtitle="These defaults are inherited by bots unless a bot override is configured." />{providers.isLoading || ai.isLoading ? <LoadingState /> : providers.isError || ai.isError ? <Card>Could not load workspace defaults.</Card> : <div className="space-y-4"><Card><h2 className="font-semibold">Stripe</h2><p className="mt-1 text-sm text-neutral-400">Card payments and subscriptions</p><div className="mt-3 grid gap-4 lg:grid-cols-2">{(["TEST", "LIVE"] as const).map((mode) => <StripeMode key={mode} mode={mode} row={providers.data?.find((item) => item.provider === "STRIPE" && item.mode === mode)} />)}</div></Card><Card><h2 className="font-semibold">Telegram Stars</h2><p className="mt-1 text-sm text-neutral-400">{providers.data?.find((item) => item.provider === "TELEGRAM_STARS" && item.mode === "LIVE")?.status || "NOT_CONFIGURED"}</p></Card><AiConfig /></div>}</AppShell>; }
function StripeMode({ mode, row }: { mode: "TEST" | "LIVE"; row?: Awaited<ReturnType<typeof botBillingApi.workspaceProviders>>[number] }) { const qc = useQueryClient(); const [publicKey, setPublicKey] = useState(""); const [secretKey, setSecretKey] = useState(""); const [webhookSecret, setWebhookSecret] = useState(""); const save = useMutation({ mutationFn: () => botBillingApi.saveWorkspaceProvider("STRIPE", mode, { publicKey, secretKey, webhookSecret }), onSuccess: () => qc.invalidateQueries({ queryKey: botBillingKeys.workspaceProviders() }) }); return <section className="rounded-lg border border-neutral-800 p-3"><h3 className="font-medium">{mode === "TEST" ? "Test" : "Live"}</h3><p className="text-xs text-neutral-400">{row?.status || "NOT_CONFIGURED"} · {row?.publicKeyMasked || "No publishable key"}</p><div className="mt-3 space-y-2"><FormField label="Publishable key"><Input value={publicKey} onChange={(e) => setPublicKey(e.target.value)} placeholder={row?.publicKeyConfigured ? "Configured" : "pk_…"} /></FormField><FormField label="Secret key"><Input type="password" value={secretKey} onChange={(e) => setSecretKey(e.target.value)} placeholder={row?.secretKeyConfigured ? "Configured" : "sk_…"} /></FormField><FormField label="Webhook secret"><Input type="password" value={webhookSecret} onChange={(e) => setWebhookSecret(e.target.value)} placeholder={row?.webhookSecretConfigured ? "Configured" : "whsec_…"} /></FormField><Button disabled={save.isPending} onClick={() => save.mutate()}>Save & validate</Button></div></section>; }
function AiConfig() { const qc = useQueryClient(); const [model, setModel] = useState(""); const [apiKey, setApiKey] = useState(""); const save = useMutation({ mutationFn: () => financeAiConfigApi.saveWorkspace({ model: model || undefined, apiKey: apiKey || undefined }), onSuccess: () => qc.invalidateQueries({ queryKey: botBillingKeys.workspaceFinanceAi() }) }); return <Card><h2 className="font-semibold">Finance AI · OpenAI</h2><div className="mt-3 grid gap-3 md:grid-cols-3"><FormField label="Model"><Input value={model} onChange={(e) => setModel(e.target.value)} placeholder="Configured model" /></FormField><FormField label="API key"><Input type="password" value={apiKey} onChange={(e) => setApiKey(e.target.value)} placeholder="Configured key" /></FormField><Button className="self-end" disabled={save.isPending} onClick={() => save.mutate()}>Save & validate</Button></div></Card>; }
